name: Deploy to AWS S3 (+ CloudFront)

on:
  push:
    branches: [ main ]         # change this to different branch
  workflow_dispatch: {}

permissions:
  id-token: write              # must: allow Actions to use OIDC
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  S3_BUCKET: nexgen-test
  CLOUDFRONT_DISTRIBUTION_ID: E2F8N1U924RXMT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build (Vite)
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::277541735425:role/GitHubOIDCDeployRole

      # print current identity for troubleshooting
      - name: Who am I
        run: aws sts get-caller-identity

      - name: Upload static assets (cache long)
        run: |
          aws s3 sync dist "s3://${S3_BUCKET}" \
            --exclude "*.html" \
            --cache-control "public,max-age=31536000,immutable" \
            --delete

      - name: Upload HTML (no-cache)
        shell: bash
        run: |
          shopt -s globstar
          for f in dist/**/*.html; do
            key="${f#dist/}"
            aws s3 cp "$f" "s3://${S3_BUCKET}/${key}" \
              --cache-control "no-cache,no-store,must-revalidate" \
              --content-type "text/html"
          done

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" \
            --paths "/*"
